default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DATABASE_USERNAME"] || "root" %>
  password: <%= ENV["DATABASE_PASSWORD"] || "password" %>
  host: <%= ENV["DATABASE_HOST"] || "db" %>

development:
  <<: *default
  database: sauna_dev

test:
  <<: *default
  database: sauna_test

production:
  <<: *default
  database: sauna_prod
